// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLYQoXJ3JPLk3ZCNCEX8Gw7Wylz4-Oms',
    appId: '1:754477825720:web:a074312d9e12f7eb433e4d',
    messagingSenderId: '754477825720',
    projectId: 'event-planner-firebase-yg',
    authDomain: 'event-planner-firebase-yg.firebaseapp.com',
    storageBucket: 'event-planner-firebase-yg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztB3Lm63BEP2ktaBER8UPL1YNYGIo_pI',
    appId: '1:754477825720:android:8944df4857008c0e433e4d',
    messagingSenderId: '754477825720',
    projectId: 'event-planner-firebase-yg',
    storageBucket: 'event-planner-firebase-yg.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKF6On3vxTiluebYZaasR8I0iVAcnV5es',
    appId: '1:754477825720:ios:9a2ed5c4afff1342433e4d',
    messagingSenderId: '754477825720',
    projectId: 'event-planner-firebase-yg',
    storageBucket: 'event-planner-firebase-yg.firebasestorage.app',
    iosBundleId: 'com.esgi.eventplanner.eventPlannerFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLYQoXJ3JPLk3ZCNCEX8Gw7Wylz4-Oms',
    appId: '1:754477825720:web:37aad00dab54dabb433e4d',
    messagingSenderId: '754477825720',
    projectId: 'event-planner-firebase-yg',
    authDomain: 'event-planner-firebase-yg.firebaseapp.com',
    storageBucket: 'event-planner-firebase-yg.firebasestorage.app',
  );
}
